-- AlterTable
ALTER TABLE "Tutor" ALTER COLUMN "languages" SET NOT NULL,
ALTER COLUMN "languages" SET DATA TYPE TEXT,
ALTER COLUMN "subjects" SET NOT NULL,
ALTER COLUMN "subjects" SET DATA TYPE TEXT;
